== Preamble

A DQMH module is the main component of an architecture based on DQMH(R) framework. A DQMH module is used to implement a section of the application that has one responsibility.

DQMH(R) framework defines two different type of DQMH module.  

====
*Singleton:*

A Singleton DQMH module can have only one instance running at any given time.
====

====
*Cloneable:*

A Cloneable DQMH module can have one or multiple instances running in parallel.
====

DQMH(R) framework defines two different ways to carry data throughout the application and with both other DQMH modules and non-DQMH based code.

====
*Request events:*

A request is a code that fires an event requesting the DQMH module to do something. Multiple locations in the code can send events to the DQMH module.

Request events are many-to-one.

Requests are usually named using imperative tense.
====

====
*Broadcast events:*

A broadcast is a code that fires an event broadcasting that the DQMH module did something. Multiple Event Structures can register to handle the Broadcast Events.

Broadcast Events are one-to-many.

Broadcasts are usually named using past tense or passive voice.
====

[#dqmh-default-events]
====
*Default events:*

By default all the DQMH (R) Modules are shipped with some default events (Requests and Broadcasts). Here is the  list of this events:
 
* Start Module
* Stop Module
* Show Panel
* Hide Panel
* Show Diagram
* Status Updated
* Error Reported
* Module Did Stop
* Update Module Execution Status
* Module Did Init
* Get Module Execution Status  

If you want to learn more about default DQMH (R) Events see the https://documentation.dqmh.org/dqmh/7.0/Nomenclature.html[documentaiton].
====

NOTE: Refer to the DQMH(R) framework official https://documentation.dqmh.org/dqmh/latest[documentation] to find more details on how the framework works


The following section gives you details on the project architecture relying on this framework.
It gives you an overview of the modules' interaction and detailed information on each module.

[NOTE]
====
If your module has a helper loop, it will be listed along with the events it processes. Helper loops can be categorized as either DQMH or Custom. To ensure your helper loop adheres to DQMH guidelines see the https://documentation.dqmh.org/dqmh/7.0/AddHelperLooptoDQMHModule.html[documentaiton].

====

Graphs used in this section have the following legend:

*Components:*


[graphviz, format="png", align="center"]
....
digraph G_BF54482B34624E499422BAAF2E0A7384 {
rankdir=LR;
edge[dir=none color=aliceblue  arrowhead=box arrowtail=box style=filled penwidth=1 fontcolor=black fontsize=12]
node[color=black shape=box fontcolor=black fontsize=12]
"DQMH module / Lvlib"[label="DQMH module / Lvlib" color=black shape=component fontcolor=black fontsize=12]
"Vi"[label="Vi" color=skyblue shape=note fontcolor=black fontsize=12]
}
....

*Events:*

[graphviz, format="png", align="center"]
....
digraph G_2A2F14560C974B42B914DE4C46E58F62 {
rankdir=LR;
edge[dir=both color=black  arrowhead=normal arrowtail=none style=filled penwidth=1 fontcolor=black fontsize=12]
node[color=black shape=box fontcolor=black fontsize=12]
"0"[color=white shape=box fontcolor=black fontsize=12]
"1"[color=white shape=box fontcolor=black fontsize=12]
"2"[color=white shape=box fontcolor=black fontsize=12]
"3"[color=white shape=box fontcolor=black fontsize=12]
"4"[color=white shape=box fontcolor=black fontsize=12]
"5"[color=white shape=box fontcolor=black fontsize=12]
"4" -> "5" [label="Broadcast from a DQMH module" dir=both color=goldenrod  arrowhead=normal arrowtail=none style=dashed penwidth=1 fontcolor=black fontsize=12];
"0" -> "1" [label="Request and wait for Reply to a DQMH module" dir=both color=forestgreen  arrowhead=normal arrowtail=vee style=filled penwidth=1 fontcolor=black fontsize=12];
"2" -> "3" [label="Request to a DQMH module" dir=both color=forestgreen  arrowhead=normal arrowtail=none style=filled penwidth=1 fontcolor=black fontsize=12];
}
....

[NOTE]
====
One arrow can represent one or more events between two components
====

[NOTE]
====
Request and Request and wait for Reply are represented by only one arrow.
If there is no Request and wait for Reply, Request representation is used.
Otherwise Request and wait for Reply is used
====

*Start and Stop module callers:*

[graphviz, format="png", align="center"]
....
digraph G_C2A84B9307674C0D8301B2EFE9FAF2EF {
rankdir=LR;
edge[dir=none color=aliceblue  arrowhead=box arrowtail=box style=filled penwidth=1 fontcolor=black fontsize=12]
node[color=black shape=box fontcolor=black fontsize=12]
"20533184-BD5F-45E4-AB03-82D8972EC485"[label="Start Module" color=yellowgreen shape=note fontcolor=black fontsize=12]
"D1F33EA4-AFC8-4AA4-A373-6A3D3878427F"[label="Start Module
caller" color=black shape=component fontcolor=black fontsize=12]
"20533184-BD5F-45E4-AB03-82D8972EC485" -> "D1F33EA4-AFC8-4AA4-A373-6A3D3878427F" [label="Called by" dir=both color=yellowgreen  arrowhead=odot arrowtail=inv style=filled penwidth=1 fontcolor=black fontsize=12];
}
....

[graphviz, format="png", align="center"]
....
digraph G_BF6922DFFA214F8999DD75B11E80B98B {
rankdir=LR;
edge[dir=none color=aliceblue  arrowhead=box arrowtail=box style=filled penwidth=1 fontcolor=black fontsize=12]
node[color=black shape=box fontcolor=black fontsize=12]
"DC4B7B7F-FDBA-4F25-B16C-4EBA3F6A4CF0"[label="Stop Module" color=tomato shape=note fontcolor=black fontsize=12]
"FF4D3C19-D26E-4C57-B501-7BB52C931960"[label="Stop Module
caller" color=black shape=component fontcolor=black fontsize=12]
"DC4B7B7F-FDBA-4F25-B16C-4EBA3F6A4CF0" -> "FF4D3C19-D26E-4C57-B501-7BB52C931960" [label="Called by" dir=both color=tomato  arrowhead=odot arrowtail=inv style=dotted penwidth=1 fontcolor=black fontsize=12];
}
....
